### ISSUE TITLE
Tension not updating in blender 2.93 for shape keys

### ISSUE THREAD

**Issue by seltsamonkel** [chiragraman/mesh-tension#1]
First I would like to thank you for such a wonderful plugin, I really appreciate it! :heart: :100: 

### What I want to do
I have a character with a wrinkle displacement map driven by the `tension_compress` vertex group and animated with shape keys.
I have also set up the normal map driven by the vertex color tension map.
I want it to deform the character with realistic wrinkles when the mesh is compressed.

### What is the issue
When I'm in blender and I manually jump from one frame to another, I can see the displacement and normal update with the displacement in the compressed parts. I can also see the vertex color update when I jump manually from frame to frame. But when I render the animation, the vertex color and the vertex groups stop updating and the displacement in the compressed parts doesn't show.

### What I have tried
- enabling/disabling `always update`
- refreshing the vertex mask
- enabling/disabling `tension map`
- try only with the displacement map driven by the `tension_compress` vertex group
- try only with the displacement map driven by the `tension_map` vertex color in the shader as a normal map
- render the character with the `tension_map` vertex color as the shader's color to see if it updates or not

![mesh-tension-issue-vertex-color-not-updating](https://user-images.githubusercontent.com/20136449/125907497-c2954df0-d7b9-464d-917b-47460adcbdaa.png)

**Comment by chiragraman** [comment]
Hello there! Thanks for the clear issue description!

Just to be sure, is the mesh actually changing across the depicted rendered frames?  Is it possible for you to share a .blend for me to look at?

**Comment by chiragraman** [comment]
Hi again. I did a quick low-res render test using the weiner .blend, and it seems to render fine (both evee and cycles):

![weiner-gif](https://user-images.githubusercontent.com/1950941/126641942-7c29ef00-047f-42a2-b812-408e3b60a1ce.gif)

I did push a small update that should affect stepping through the frames in viewport, I'd flipped a flag accidentally. Maybe that should help, but that shouldn't affect rendering. From your images I'm not seeing that the mesh is updating, so the tension map shouldn't, unless I'm missing something.

**Comment by seltsamonkel** [comment]
Hello, 

I'm sorry haha. In the image I provided last time the mesh doesn't seem to change because I was very lazy and added just the first few rendered frames of the animation, and there are not enough frames to see any visible change. But in the viewport the vertex color was really changing from frame 0 to frame 1 adding red under the eyes, and that didn't appear in the render (where it all stayed green).

Now I have tried the version 1.5.5, and I've found the following problems:

- Like before the vertex color doesn't update when I render the animation (in the viewport it does) (I'm animating with blend shapes)
- With version 1.5.5 I'm getting a new error (I got the same error with Steve Miller's version) which is that when I hit render, some modifiers automatically deactivate and don't appear in the render. (If I deactivate the mesh tension plugin the modifiers don't deactivate, and they render without problems)


**Then suddenly, as I was preparing a simplified .blend file of the character for you to test, all the problems disappeared** and it worked just fine. The vertex color changed from frame to frame, and the modifiers stopped getting disabled. I suppose it's because my character is too complex and has too many modifiers? 

With this information, I suspect that what's happening is that the plugin deactivates some modifiers and itself (and that's why it doesn't seem to work) when the geometry of the model is too complex. Then, when the geometry is simple everything seems to work perfect.
Any ideas how to fix this issue?

I hope this helps, and again, thank you so much for taking the time!

![mesh-deform-github-test3](https://user-images.githubusercontent.com/20136449/126929164-a1e47148-adf2-4a66-b62d-5611a30f1e42.png)
![mesh-deform-github-test2](https://user-images.githubusercontent.com/20136449/126929171-20493d6f-dd61-4a9d-a5aa-995a442c4239.png)

**Comment by chiragraman** [comment]
Thanks for the update! Sorry to hear it's not working for you, but it seems like we have some more information to get to the bottom of it :)

> In the image I provided last time the mesh doesn't seem to change because I was very lazy and added just the first few rendered frames of the animation, and there are not enough frames to see any visible change. 

No worries, it takes time to put these images together, so I understand.

I'm indeed temporarily suspending generative modifiers for computing tension (also any modifiers you mark with `SKIPTENSION` suffix at the end). This is done in the `pre` frame change or depsgraph update handler. At the end of the tension computation these are then restored to their original state. Here is the list of modifiers suspended:
https://github.com/chiragraman/mesh-tension/blob/a30b7409a3434c3202828796c6fc415490e2bb8f/mesh_tension.py#L38-L42

There was an issue with Steve's script in 1.5.1 [where the pre computation wasn't run on all objects, but I fixed this in 1.5.3, and he also fixed it in 1.5.2, so I don't think that's the issue](https://blenderartists.org/t/revised-mesh-tension-add-on/1239091/68?u=calanir). 

A couple questions:
1. Just to confirm, it seems like there are no crashes right? The main issue is that the tension doesn't show up?
2. Once the changes do not show up in renders, do you see that the modifier settings in the viewport have not been restored? 
3. The version with just the head, does it have a different set of modifiers than the rest of the character, or the main difference between the simplified and original versions is the number of polygons?
4. If there are indeed different set of modifiers, could you try marking the balance with the `SKIPTENSION` suffix in the original and see if that works? 


I'll try and look into the code again after work to try and imagine what might be happening. If you can share a blend where the problem occurs, it might be easier to try and debug by stepping through the code. If the issue is sharing the character, maybe you can replace it with a free mesh online and share it if you can reproduce the issue?

**Comment by seltsamonkel** [comment]
Hello and thank you for your time :)

It makes sense that the code is somehow responsible, because the modifiers that fail are always Subsurface, Displacement (the one that uses the vertex group) and Triangulate.

To answer your questions:

1. It's hard to confirm whether there are no crashes, because when they happen (at least when I use Steve's version) it happens after some random number of rendered frames. I haven't had time to render many frames using your plugin because of the issues I encountered.

2. Yes, the render starts without the modifiers, and they stay disabled for the rest of the render. They continue being disabled even after the render is cancelled (unless I cancel it right away. In this case they turn themselves back on)

3. The head version has a lot less modifiers (I deleted all the hair particles, some skin-wraps for the eye sockets and the teeth gums) and a lot less geometry (I deleted the body from the neck down, the cornea and the teeth). The important modifiers (subdivision, displacement, triangulate, and such) are the same in both files.

4. I'm sorry I don't know how to do that :(

I'm open to sharing the file, although I'd prefer to DM it to you.

Thanks!

**Comment by chiragraman** [comment]
Hi, thanks for the details :)

1. Ah, I see. Yeah we can revisit this one once the other issues are fixed. 
2. Hmm, I see. I'll check if I can isolate the render cancelling behavior independently. 
3. This is good to know, and a good stress test. 
4. Ah, so you add something like "_SKIPTENSION" to the end of the name of the modifier. Steve introduced this in v1.3 I think, and I kept it as is. [Here ](https://blenderartists.org/uploads/default/original/4X/a/e/e/aee8aca847d24d2bc7be32d97dd1acea8f309854.png) is a screenshot in case it helps.

**Comment by chiragraman** [comment]
Updating here after an offline discussion with @seltsamonkel, it seems like there is a conflict with the GoB plugin (https://github.com/JoseConseco/GoB/wiki). Turning that off fixes the rendering issue. I'll look into why this is a problem and update.
